#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

# Apply database migrations
python3 manage.py migrate --no-input

# Start Gunicorn (production-ready)
exec gunicorn --bind 0.0.0.0:8000 kaka.wsgi:application --workers 4
