#!/bin/bash

set -o errexit
set -o nounset

# Wait until Celery workers are ready
worker_ready(){
    celery -A kaka inspect ping
}

until worker_ready; do 
    >&2 echo 'Celery workers not available :-('
    sleep 1
done

>&2 echo 'Celery workers are available and ready!...:-)'

# Set Flower environment variables
export CELERY_BROKER_URL="${CELERY_BROKER}"
export FLOWER_PORT=5555
export FLOWER_ADDRESS=0.0.0.0

# Start Flower
python -m flower --broker="$CELERY_BROKER_URL" --port="$FLOWER_PORT" --address="$FLOWER_ADDRESS"
